name: Setup ArgoCD
on: 
  workflow_dispatch: 
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - uses: Azure/k8s-deploy@v5
      with:
          manifests: |
            argo-ha/install.yaml
          namespace: argocd
    - uses: Azure/k8s-deploy@v5
      with:
          manifests: |
            argo-ha/argocd-application.yaml
          namespace: argocd